version: "3.9"
services:
       app-postgres:
           container_name: app-postgres
           build: .
           restart: always
           depends_on:
            - postgres-db
           ports:
             - "3000:3000"
           links:
             - postgres-db
       postgres-db:
             container_name: postgres-db
             environment:
               - POSTGRES_HOST_AUTH_METHOD=trust
               - POSTGRES_PASSWORD=contohlagi
               - POSTGRES_USER=sangsakawira
               - APP_DB_NAME=perumahan
             image: postgres
             volumes:
               - ./data:/data/db
             ports:
               - '6666:5432'