version: "3"
services:
       app-postgres:
           container_name: app-postgres
           build: .
           restart: always
           environment: 
            - DB_URL=postgres-db
            - SECRET_KEY=a2n!h24no23n
           depends_on:
            - postgres-db
           ports:
             - "3000:3000"
           links:
             - postgres-db
       postgres-db:
             container_name: postgres-db
             environment:
               - POSTGRES_PASSWORD=contohpassword
               - POSTGRES_USER=sangsakawira
               - POSTGRES_DB=perumahan
             image: postgres
             ports:
              - "5000:5432"
             volumes:
               - ./data:/data/db